logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME:}
    password: ${JDBC_DATABASE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port : ${PORT:8080}