logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG
mvc:
  hiddenmethod:
    filter:
      enabled: true


spring:
  datasource:
    password: ${JDBC_DATABASE_PASSWORD:}
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME:}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port : ${PORT:8080}